export type SoundTranslateValue = string | readonly string[];
export type SoundTranslateMap = Record<string, SoundTranslateValue>;

export const sounds_translate_key: SoundTranslateMap = {
  minecraft: "Minecraft",

  block: "方块",
  entity: "实体",
  player: "玩家",
  item: "物品",
  ambient: "环境",
  music: "音乐",
  ui: "界面",
  weather: "天气",
  voice: "语音",
  record: "唱片",
  particle: "粒子",
  event: "事件",
  random: "随机",
  hostile: "敌对",
  neutral: "中立",
  passive: "被动",
  generic: "通用",
  sound: "声音",
  game: "游戏",
  blocks: "方块",
  creative: "创造模式",
  menu: "菜单",
  hud: "抬头显示",

  overworld: "主世界",
  nether: "下界",
  end: "末地",
  underwater: "水下",
  under_water: "水下",
  cave: "洞穴",
  badlands: "恶地",
  bamboo_jungle: "竹林",
  basalt_deltas: "玄武岩三角洲",
  cherry_grove: "樱花树林",
  crimson_forest: "绯红森林",
  deep_dark: "深暗之域",
  desert: "沙漠",
  dripstone_caves: "溶洞",
  flower_forest: "繁花森林",
  forest: "森林",
  frozen_peaks: "冰封山峰",
  grove: "雪林",
  jagged_peaks: "尖峭山峰",
  jungle: "丛林",
  lush_caves: "繁茂洞穴",
  meadow: "草甸",
  nether_wastes: "下界荒地",
  old_growth_taiga: "原始针叶林",
  soul_sand_valley: "灵魂沙峡谷",
  sparse_jungle: "稀疏丛林",
  stony_peaks: "裸岩山峰",
  swamp: "沼泽",
  warped_forest: "诡异森林",
  snowy_slopes: "积雪的山坡",

  use: ["使用", "操作"],
  work: ["工作", "劳作"],
  click: "点击",
  press: "按下",
  release: "松开",
  activate: "激活",
  deactivate: ["停用", "取消激活"],
  insert: ["放入", "插入"],
  remove: ["移除", "取出"],
  take: ["拿取", "取出"],
  put: ["放入", "放置"],
  lock: "上锁",
  unlock: "解锁",
  loop: "循环",
  exit: "退出",
  in: "进入",
  out: "离开",
  enter: "进入",
  inside: "内部",
  return: "返回",
  travel: "行进",
  additions: "附加音效",
  mood: "氛围",
  rare: "稀有",
  ultra_rare: "极稀有",
  ominous: "不祥",
  ambient_ominous: "不祥环境音",

  hurt: "受伤",
  death: "死亡",
  attack: "攻击",
  shoot: "射击",
  hit: "击中",
  break: "破坏",
  place: "放置",
  open: "打开",
  close: "关闭",
  step: "脚步",
  fall: "摔落",
  jump: "跳跃",
  land: "落地",
  swim: "游泳",
  splash: "飞溅",
  drink: "饮用",
  eat: "进食",
  levelup: "升级",
  explode: "爆炸",
  thunder: "雷声",
  rain: "雨声",
  burn: "燃烧",
  extinguish: "熄灭",
  ignite: "点燃",
  charge: "蓄力",
  roar: "咆哮",
  growl: "低吼",
  scream: "尖叫",
  cry: "哭喊",
  laugh: "笑声",
  breathe: "呼吸",
  snore: "打鼾",
  breath: "呼吸",
  inhale: "吸气",
  pant: "喘气",
  hiss: "嘶嘶声",
  whine: "呜咽",
  purr: "呼噜声",
  purreow: "呼噜喵叫",
  chirp: "啁啾",
  screech: "尖啸",
  shriek: "尖啸",
  sniff: "嗅探",
  sniffing: "嗅探",
  snip: "剪动",
  sneeze: "打喷嚏",
  pre_sneeze: "准备打喷嚏",
  spit: "吐口水",
  squirt: "喷射",
  sting: "蜇刺",
  bite: "啃咬",
  flop: "扑腾",
  flap: "扇动翅膀",
  fly: "飞行",
  flying: "飞行",
  takeoff: "起飞",
  swoop: "俯冲",
  gallop: "疾驰",
  gallop_water: "水中疾驰",
  riding: "骑乘",
  paddle_land: "陆地划桨",
  paddle_water: "水中划桨",
  step_lava: "踏入熔岩",
  step_sand: "踩踏沙子",
  step_water: "涉水",
  step_wood: "踩踏木头",
  big_fall: "重摔",
  small_fall: "轻摔",
  hit_ground: "撞击地面",
  hurt_land: "陆地受伤",
  hurt_water: "水中受伤",
  hurt_drown: "溺水受伤",
  hurt_freeze: "冰冻受伤",
  hurt_on_fire: "着火受伤",
  hurt_sweet_berry_bush: "甜浆果丛刺伤",
  hurt_baby: "幼体受伤",
  hurt_small: "轻微受伤",
  hurt_reduced: "伤害减免",
  death_land: "陆地死亡",
  death_water: "水中死亡",
  death_baby: "幼体死亡",
  death_small: "小型生物死亡",
  attack_impact: "攻击命中",
  prepare_attack: "准备攻击",
  knockback: "击退",
  crit: "暴击",
  sweep: "横扫攻击",
  deflect: "弹开",
  damage: "受到伤害",
  nodamage: "未造成伤害",
  aggressive_ambient: "攻击性环境声",
  aggro: "进入敌对状态",
  angry: "愤怒",
  agitated: "焦躁",
  happy: "高兴",
  jealous: "嫉妒",
  worried_ambient: "担忧环境声",
  idle: "闲置",
  idle_air: "空中闲置",
  idle_ground: "地面闲置",
  idle_water: "水中闲置",
  ambient_land: "陆地环境声",
  ambient_water: "水中环境声",
  ambient_baby: "幼体环境声",
  ambient_with_item: "持有物品环境声",
  ambient_without_item: "未持物品环境声",
  imitate: "模仿",
  celebrate: "庆祝",
  screaming: "尖叫型",
  stare: "凝视",
  warn: "警告",
  warning: "警告",
  retreat: "撤退",
  emerge: "钻出",
  spawn: "生成",
  despawn: "消失",
  appeared: "出现",
  disappeared: "消失",
  reappeared: "重新出现",
  teleport: "传送",
  convert: "转化",
  converted: "完成转化",
  converted_to_drowned: "转化为溺尸",
  converted_to_stray: "转化为流浪者",
  converted_to_zombie: "转化为僵尸",
  converted_to_zombified: "转化为僵尸猪灵",
  infect: "感染",
  cure: "治愈",
  grow: "生长",
  grow_up: "长大",
  lay_egg: "产卵",
  lay_spawn: "产下卵块",
  hatch: "孵化",
  pollinate: "授粉",
  beg_for_food: "乞食",
  cant_breed: "无法繁殖",
  sit: "坐下",
  stand: "站起",
  sleep: "睡觉",
  shake: "甩水",
  roll: "翻滚",
  unroll_start: "开始展开",
  unroll_finish: "完成展开",
  sway: "摇摆",
  twitch: "抽动",
  tongue: "伸舌",
  heartbeat: "心跳",
  sonic_boom: "音波尖啸",
  sonic_charge: "音波蓄力",
  dig: "挖掘",
  digging: "挖掘",
  digging_stop: "停止挖掘",
  brush: "刷扫",
  brushing: "刷扫",
  scrape: "刮除",
  wax_on: "涂蜡",
  wax_off: "除蜡",
  waxed_interact_fail: "已涂蜡无法操作",
  strip: "去皮",
  flatten: "铲平",
  till: "耕地",
  plant: "种植",
  crop: "作物",
  bloom: "盛开",
  extinguish_fire: "灭火",
  fire_crackle: "火焰噼啪",
  crackle: "噼啪声",
  crack: "破裂",
  shatter: "碎裂",
  resonate: "共振",
  drip: "滴落",
  drip_lava: "熔岩滴落",
  drip_water: "水滴落",
  drip_lava_into_cauldron: "熔岩滴入炼药锅",
  drip_water_into_cauldron: "水滴入炼药锅",
  bubble_pop: "气泡破裂",
  pop: "破裂声",
  plop: "扑通声",
  squish: "挤压",
  squish_small: "轻微挤压",
  splash_potion: "喷溅药水",
  freeze: "冻结",
  unfreeze: "解冻",
  dries: "变干",
  burnout: "熄灭",
  blow_out: "吹灭",
  blow_up: "爆炸",
  blast: "爆炸声",
  blast_far: "远处爆炸声",
  large_blast: "大型爆炸",
  large_blast_far: "远处大型爆炸",
  lightning_bolt: "闪电",
  wind_burst: "风爆",
  whirl: "旋风",
  click_on: "开启点击",
  click_off: "关闭点击",
  clicking: "连续点击",
  clicking_stop: "停止点击",
  throw: "投掷",
  launch: "发射",
  pickup: "拾取",
  fill: "装满",
  empty: "倒空",
  shear: "剪毛",
  dash: "冲刺",
  dash_ready: "准备冲刺",
  dash_land: "冲刺落地",
  dash_ready_land: "落地后准备冲刺",
  long_jump: "长跳",
  spin: "旋转",
  slide: "滑动",
  impact: "撞击",
  ram_impact: "冲撞命中",
  prepare_ram: "准备冲撞",
  primed: "已点燃",
  ready: "准备就绪",
  complete: "完成",
  fail: "失败",
  strong: "强力",
  weak: "虚弱",
  high_speed: "高速",
  short: "短促",
  far: "远处",
  above: "上方",
  nearby_close: "附近较近",
  nearby_closer: "附近更近",
  nearby_closest: "附近最近",
  open_long: "长音打开",
  close_long: "长音关闭",
  open_shutter: "打开遮板",
  close_shutter: "关闭遮板",
  turn_on: "开启",
  turn_off: "关闭",
  extend: "伸出",
  contract: "收回",
  attach: "附着",
  detach: "脱离",
  tied: "拴住",
  untied: "解开拴绳",
  insert_item: "放入物品",
  insert_item_fail: "放入物品失败",
  insert_fail: "放入失败",
  eject_item: "弹出物品",
  add_item: "添加物品",
  remove_item: "移除物品",
  remove_one: "移除一个",
  take_item: "拿取物品",
  take_result: "取出成品",
  rotate_item: "旋转物品",
  place_item: "放置物品",
  item_drop: "物品掉落",
  item_given: "给予物品",
  item_taken: "取走物品",
  item_thrown: "扔出物品",
  item_no_drop: "物品未掉落",
  drop_contents: "倒出内容物",
  drop_seed: "掉落种子",
  spawn_item: "生成物品",
  spawn_item_begin: "开始生成物品",
  about_to_spawn_item: "即将生成物品",
  no_item_get: "无物品并取回",
  no_item_no_get: "无物品且未取回",
  multi_swap: "批量交换",
  single_swap: "单个交换",
  mirror_move: "镜像移动",
  craft: "合成",
  dispense: "发射物品",
  dispose: "丢弃",
  repair: "修复",
  enchanted: "已附魔",
  curse: "诅咒",
  absorb: "吸收",
  deplete: "耗尽",
  retrieve: "取回",
  add_candle: "插上蜡烛",
  carve: "雕刻",
  destroy: "摧毁",
  break_block: "破坏方块",
  attack_iron_door: "攻击铁门",
  attack_wooden_door: "攻击木门",
  break_wooden_door: "破坏木门",
  place_in_water: "放入水中",
  detect_player: "检测到玩家",
  reject_rewarded_player: "拒绝已获奖励的玩家",
  select_pattern: "选择纹饰",
  select_recipe: "选择配方",
  power_select: "选择能力",
  page_turn: "翻页",
  toast: ["提示消息", "弹出提示"],
  challenge_complete: "挑战完成",
  set_spawn: "设置出生点",
  trigger: "触发",
  transition: "状态转换",
  wait: "等待",
  play: "播放",
  loading_start: "开始装载",
  loading_middle: "装载中",
  loading_end: "完成装载",
  locked: "已锁定",
  drink_milk: "饮用奶",
  drink_potion: "饮用药水",
  milk: "奶",
  brew: "酿造",
  burp: "打嗝",
  fish: "鱼",
  egg: "蛋",
  egg_break: "蛋破裂",
  egg_crack: "蛋开裂",
  egg_hatch: "蛋孵化",
  destroy_egg: "摧毁蛋",
  horn: "号角",
  horn_break: "号角损坏",
  goat_horn: "山羊角",
  mob_effect: "状态效果",
  bad_omen: "不祥之兆",
  raid_omen: "袭击之兆",
  trial_omen: "试炼之兆",
  raid: "袭击",
  cast_spell: "施法",
  prepare_blindness: "准备施加失明",
  prepare_mirror: "准备镜像",
  prepare_summon: "准备召唤",
  prepare_wololo: "准备转换羊的颜色",
  listening: "倾听",
  listening_angry: "愤怒倾听",
  scenting: "闻嗅",
  searching: "搜寻",
  peek: "探头",
  shamble: "蹒跚",
  shamble_baby: "幼体蹒跚",
  smash_air: "重击挥空",
  smash_ground: "重击地面",
  smash_ground_heavy: "强力重击地面",
  stunned: "眩晕",
  soul_escape: "灵魂逃逸",
  spread: "蔓延",
  target: "锁定目标",
  tears: "泪水",
  tendril_clicks: "卷须咔嗒声",
  thorns: "荆棘反伤",
  tilt_down: "向下倾斜",
  tilt_up: "向上倾斜",
  twinkle: "闪烁",
  twinkle_far: "远处闪烁",
  upwards_ambient: "上升环境声",
  upwards_inside: "内部上升",
  whirlpool_ambient: "漩涡环境声",
  whirlpool_inside: "漩涡内部声",
  harness_goggles_down: "放下挽具护目镜",
  harness_goggles_up: "抬起挽具护目镜",
  lunge_1: "突刺一级",
  lunge_2: "突刺二级",
  lunge_3: "突刺三级",
  stop_using: "停止使用",
  suspicious_milk: "可疑的奶",
  trade: "交易",
  yes: "肯定",
  no: "否定",
  admiring_item: "欣赏物品",
  pick_berries: "采摘浆果",
  stray_ambient: "流浪者环境声",
  empty_axolotl: "倒出美西螈",
  empty_fish: "倒出鱼",
  empty_lava: "倒出熔岩",
  empty_powder_snow: "倒出细雪",
  empty_tadpole: "倒出蝌蚪",
  fill_axolotl: "装入美西螈",
  fill_dragonbreath: "收集龙息",
  fill_fish: "装入鱼",
  fill_lava: "装入熔岩",
  fill_powder_snow: "装入细雪",
  fill_success: "成功装入",
  fill_tadpole: "装入蝌蚪",
  hit_player: "击中玩家",
  hurt_closed: "闭合时受伤",
  jump_small: "小幅跳跃",
  jump_water: "水中跳跃",
  loop_aggressive: "攻击状态循环",
  smoke: "冒烟",
  spawn_mob: "生成生物",

  arrow: "箭",
  bow: "弓",
  crossbow: "弩",
  trident: "三叉戟",
  shield: "盾",
  axe: "斧",
  hoe: "锄",
  shovel: "锹",
  shears: "剪刀",
  mace: "重锤",
  spear: "长矛",
  spear_wood: "木矛",
  saddle: "鞍",
  lead: "拴绳",
  elytra: "鞘翅",
  spyglass: "望远镜",
  fishing_bobber: "鱼钩",
  snowball: "雪球",
  ender_pearl: "末影珍珠",
  ender_eye: "末影之眼",
  totem: "不死图腾",
  bundle: "收纳袋",
  bucket: "桶",
  bottle: "瓶子",
  experience_bottle: "附魔之瓶",
  experience_orb: "经验球",
  honey_bottle: "蜂蜜瓶",
  ominous_bottle: "不祥之瓶",
  lingering_potion: "滞留药水",
  ink_sac: "墨囊",
  honeycomb: "蜜脾",
  scute_drop: "鳞甲掉落",
  horse_armor: "马铠",
  wolf_armor: "狼铠",
  llama_carpet: "羊驼地毯",
  nautilus_saddle_equip: "装备鹦鹉螺鞍",
  nautilus_saddle_underwater_equip: "水下装备鹦鹉螺鞍",
  equip_chain: "装备锁链盔甲",
  equip_copper: "装备铜盔甲",
  equip_diamond: "装备钻石盔甲",
  equip_elytra: "装备鞘翅",
  equip_generic: "装备盔甲",
  equip_gold: "装备金盔甲",
  equip_iron: "装备铁盔甲",
  equip_leather: "装备皮革盔甲",
  equip_nautilus: "装备鹦鹉螺盔甲",
  equip_netherite: "装备下界合金盔甲",
  equip_turtle: "装备海龟壳",
  equip_wolf: "装备狼铠",
  unequip: "卸下装备",
  unequip_nautilus: "卸下鹦鹉螺装备",
  unequip_wolf: "卸下狼铠",
  quick_charge_1: "快速装填一级",
  quick_charge_2: "快速装填二级",
  quick_charge_3: "快速装填三级",
  riptide_1: "激流一级",
  riptide_2: "激流二级",
  riptide_3: "激流三级",
  wind_charge: "风弹",
  firework_rocket: "烟花火箭",
  dragon_fireball: "末影龙火球",

  note: "音符",
  note_block: "音符盒",
  harp: "竖琴",
  bell: "铃声",
  bass: "贝斯",
  hat: "踩镲",
  snare: "军鼓",
  chime: "风铃",
  flute: "长笛",
  guitar: "吉他",
  xylophone: "木琴",
  iron_xylophone: "铁木琴",
  cow_bell: "牛铃",
  didgeridoo: "迪吉里杜管",
  bit: "比特音色",
  banjo: "班卓琴",
  pling: "叮咚",
  basedrum: "底鼓",
  music_disc: "音乐唱片",
  creator: "创作者",
  creator_music_box: "创作者音乐盒版",
  precipice: "悬崖",
  relic: "遗迹",
  otherside: "另一侧",
  pigstep: "猪灵之舞",
  mellohi: ["梅洛希", "Mellohi"],
  stal: ["斯塔尔", "Stal"],
  strad: ["斯特拉德", "Strad"],
  ward: ["沃德", "Ward"],

  door: "门",
  trapdoor: "活板门",
  gate: "栅栏门",
  chest: "箱子",
  barrel: "木桶",
  anvil: "铁砧",
  furnace: "熔炉",
  brewing: "酿造",
  enchant: "附魔",
  enchantment: "附魔",
  enchantment_table: "附魔台",
  smithing: "锻造",
  smithing_table: "锻造台",
  grindstone: "砂轮",
  beehive: "蜂箱",
  beacon: "信标",
  piston: "活塞",
  dispenser: "发射器",
  dropper: "投掷器",
  lever: "拉杆",
  button: "按钮",
  pressure_plate: "压力板",
  wooden_button: "木质按钮",
  stone_button: "石质按钮",
  wooden_door: "木门",
  iron_door: "铁门",
  copper_door: "铜门",
  wooden_trapdoor: "木质活板门",
  iron_trapdoor: "铁活板门",
  copper_trapdoor: "铜活板门",
  fence_gate: "栅栏门",
  wooden_pressure_plate: "木质压力板",
  stone_pressure_plate: "石质压力板",
  metal_pressure_plate: "金属压力板",
  brewing_stand: "酿造台",
  blastfurnace: "高炉",
  smoker: "烟熏炉",
  stonecutter: "切石机",
  cartography_table: "制图台",
  loom: "织布机",
  composter: "堆肥桶",
  crafter: "合成器",
  comparator: "红石比较器",
  redstone_torch: "红石火把",
  conduit: "潮涌核心",
  respawn_anchor: "重生锚",
  lodestone: "磁石",
  ender_chest: "末影箱",
  shulker_box: "潜影盒",
  item_frame: "物品展示框",
  glow_item_frame: "荧光物品展示框",
  armor_stand: "盔甲架",
  decorated_pot: "饰纹陶罐",
  chiseled_bookshelf: "雕纹书架",
  shelf: ["置物架", "架子"],
  spawner: "刷怪笼",
  trial_spawner: "试炼刷怪笼",
  vault: "宝库",
  ominous_activate: "不祥激活",
  copper_bulb: "铜灯泡",
  copper_chest: "铜箱",
  copper_chest_weathered: "锈蚀的铜箱",
  copper_chest_oxidized: "氧化的铜箱",
  copper_grate: "铜格栅",
  creaking_heart: "嘎枝之心",
  heavy_core: "沉重核心",
  campfire: "营火",
  candle: "蜡烛",
  cake: "蛋糕",
  ladder: "梯子",
  lantern: "灯笼",
  scaffolding: "脚手架",
  sign: "告示牌",
  hanging_sign: "悬挂式告示牌",
  tripwire: "绊线",
  tnt: "TNT",
  portal: "传送门",
  end_portal: "末地传送门",
  end_gateway: "末地折跃门",
  end_portal_frame: "末地传送门框架",
  chorus_flower: "紫颂花",
  chorus_fruit: "紫颂果",

  stone: "石头",
  wood: "木头",
  wooden: "木质",
  metal: "金属",
  glass: "玻璃",
  sand: "沙子",
  gravel: "沙砾",
  dirt: "泥土",
  grass: "草方块",
  snow: "雪",
  ice: "冰",
  wool: "羊毛",
  slime: "史莱姆",
  honey: "蜂蜜",
  iron: "铁",
  copper: "铜",
  chain: "锁链",
  basalt: "玄武岩",
  calcite: "方解石",
  deepslate: "深板岩",
  deepslate_bricks: "深板岩砖",
  deepslate_tiles: "深板岩瓦",
  polished_deepslate: "磨制深板岩",
  tuff: "凝灰岩",
  polished_tuff: "磨制凝灰岩",
  tuff_bricks: "凝灰岩砖",
  blackstone: "黑石",
  gilded_blackstone: "镶金黑石",
  netherrack: "下界岩",
  nether_bricks: "下界砖",
  nether_gold_ore: "下界金矿石",
  nether_ore: "下界矿石",
  netherite_block: "下界合金块",
  ancient_debris: "远古残骸",
  bone_block: "骨块",
  coral_block: "珊瑚块",
  amethyst_block: "紫水晶块",
  amethyst_cluster: "紫水晶簇",
  small_amethyst_bud: "小型紫晶芽",
  medium_amethyst_bud: "中型紫晶芽",
  large_amethyst_bud: "大型紫晶芽",
  dripstone_block: "滴水石块",
  pointed_dripstone: "滴水石锥",
  magma_cube: "岩浆怪",
  slime_block: "黏液块",
  honey_block: "蜂蜜块",
  sponge: "海绵",
  wet_sponge: "湿海绵",
  cobweb: "蜘蛛网",
  powder_snow: "细雪",
  soul_sand: "灵魂沙",
  soul_soil: "灵魂土",
  mud: "泥巴",
  packed_mud: "夯实泥土",
  mud_bricks: "泥砖",
  resin: "树脂",
  resin_bricks: "树脂砖",
  dry_grass: "枯草",
  wet_grass: "湿草",
  azalea: "杜鹃花丛",
  flowering_azalea: "盛开的杜鹃花丛",
  azalea_leaves: "杜鹃树叶",
  bamboo: "竹子",
  bamboo_sapling: "竹笋",
  bamboo_wood: "竹制木头",
  big_dripleaf: "大型垂滴叶",
  small_dripleaf: "小型垂滴叶",
  cave_vines: "洞穴藤蔓",
  cherry_leaves: "樱花树叶",
  cherry_sapling: "樱花树苗",
  cherry_wood: "樱花木",
  deadbush: "枯萎的灌木",
  eyeblossom: "眼眸花",
  firefly_bush: "萤火虫灌木丛",
  frogspawn: "青蛙卵",
  fungus: "菌",
  hanging_roots: "垂根",
  leaf_litter: "落叶",
  lily_pad: "睡莲",
  mangrove_roots: "红树根",
  muddy_mangrove_roots: "沾泥的红树根",
  moss: "苔藓块",
  moss_carpet: "苔藓地毯",
  nether_sprouts: "下界苗",
  nether_wart: "下界疣",
  nylium: "菌岩",
  pale_hanging_moss: "苍白垂须",
  pink_petals: "粉红色花簇",
  rooted_dirt: "缠根泥土",
  roots: "菌索",
  shroomlight: "菌光体",
  spore_blossom: "孢子花",
  stem: "菌柄",
  sweet_berry_bush: "甜浆果丛",
  vine: "藤蔓",
  wart_block: "疣块",
  weeping_vines: "垂泪藤",
  froglight: "蛙明灯",
  cactus_flower: "仙人掌花",
  pumpkin: "南瓜",
  growing_plant: "植物生长",
  pale_moss: "苍白苔藓",
  sculk: "幽匿块",
  sculk_catalyst: "幽匿催发体",
  sculk_sensor: "幽匿感测体",
  sculk_shrieker: "幽匿尖啸体",
  sculk_vein: "幽匿脉络",
  bubble_column: "气泡柱",
  suspicious_gravel: "可疑的沙砾",
  suspicious_sand: "可疑的沙子",
  parched: "干涸",
  bamboo_wood_button: "竹按钮",
  bamboo_wood_door: "竹门",
  bamboo_wood_fence_gate: "竹栅栏门",
  bamboo_wood_hanging_sign: "竹悬挂式告示牌",
  bamboo_wood_pressure_plate: "竹压力板",
  bamboo_wood_trapdoor: "竹活板门",
  cherry_wood_button: "樱花木按钮",
  cherry_wood_door: "樱花木门",
  cherry_wood_fence_gate: "樱花木栅栏门",
  cherry_wood_hanging_sign: "樱花木悬挂式告示牌",
  cherry_wood_pressure_plate: "樱花木压力板",
  cherry_wood_trapdoor: "樱花木活板门",
  nether_wood: "下界木",
  nether_wood_button: "下界木按钮",
  nether_wood_door: "下界木门",
  nether_wood_fence_gate: "下界木栅栏门",
  nether_wood_hanging_sign: "下界木悬挂式告示牌",
  nether_wood_pressure_plate: "下界木压力板",
  nether_wood_trapdoor: "下界木活板门",
  copper_golem_statue: "铜傀儡雕像",
  copper_golem_weathered: "锈蚀的铜傀儡",
  copper_golem_oxidized: "氧化的铜傀儡",
  copper_golem_become_statue: "铜傀儡变为雕像",

  boat: "船",
  book: "书",
  minecart: "矿车",
  painting: "画",
  lodestone_compass: "磁石指针",
  sniffer_egg: "嗅探兽蛋",
  dragon: "末影龙",
  end_flash: "末地闪光",
  credits: "制作人员名单",
  lava_chicken: "熔岩鸡",
  mall: ["商场", "Mall"],
  swag: "装饰",

  lava: "岩浆",
  water: "水",
  fire: "火",
  wind: "风",

  villager: "村民",
  armorer: "盔甲匠",
  butcher: "屠夫",
  cartographer: "制图师",
  cleric: ["牧师", "祭司"],
  farmer: "农民",
  fisherman: "渔夫",
  fletcher: "制箭师",
  leatherworker: "皮匠",
  librarian: "图书管理员",
  mason: "石匠",
  shepherd: "牧羊人",
  toolsmith: "工具匠",
  weaponsmith: "武器匠",
  work_armorer: "盔甲匠工作",
  work_butcher: "屠夫工作",
  work_cartographer: "制图师工作",
  work_cleric: "牧师工作",
  work_farmer: "农民工作",
  work_fisherman: "渔夫工作",
  work_fletcher: "制箭师工作",
  work_leatherworker: "皮匠工作",
  work_librarian: "图书管理员工作",
  work_mason: "石匠工作",
  work_shepherd: "牧羊人工作",
  work_toolsmith: "工具匠工作",
  work_weaponsmith: "武器匠工作",
  zombie: "僵尸",
  skeleton: "骷髅",
  creeper: "苦力怕",
  spider: "蜘蛛",
  enderman: "末影人",
  blaze: "烈焰人",
  witch: "女巫",
  pig: "猪",
  cow: "牛",
  sheep: "羊",
  chicken: "鸡",
  horse: "马",
  cat: "猫",
  wolf: "狼",
  fox: "狐狸",
  bee: "蜜蜂",
  golem: "傀儡",
  allay: "悦灵",
  armadillo: "犰狳",
  axolotl: "美西螈",
  bat: "蝙蝠",
  bogged: "沼骸",
  breeze: "旋风人",
  camel: "骆驼",
  camel_husk: ["骆驼尸壳", "尸壳骆驼"],
  cod: "鳕鱼",
  copper_golem: "铜傀儡",
  creaking: "嘎枝",
  dolphin: "海豚",
  donkey: "驴",
  dried_ghast: "干燥恶魂",
  drowned: "溺尸",
  elder_guardian: "远古守卫者",
  ender_dragon: "末影龙",
  endermite: "末影螨",
  evoker: "唤魔者",
  evoker_fangs: "唤魔者尖牙",
  frog: "青蛙",
  ghast: "恶魂",
  ghastling: ["恶魂幼体", "小恶魂"],
  glow_squid: "发光鱿鱼",
  goat: "山羊",
  guardian: "守卫者",
  happy_ghast: "快乐恶魂",
  hoglin: "疣猪兽",
  husk: "尸壳",
  illusioner: "幻术师",
  iron_golem: "铁傀儡",
  llama: "羊驼",
  mooshroom: "哞菇",
  mule: "骡",
  nautilus: "鹦鹉螺",
  ocelot: "豹猫",
  panda: "熊猫",
  parrot: "鹦鹉",
  phantom: "幻翼",
  piglin: "猪灵",
  piglin_brute: "猪灵蛮兵",
  pillager: "掠夺者",
  polar_bear: "北极熊",
  puffer_fish: "河豚",
  rabbit: "兔子",
  ravager: "劫掠兽",
  salmon: "鲑鱼",
  shulker: "潜影贝",
  shulker_bullet: "潜影弹",
  silverfish: "蠹虫",
  skeleton_horse: "骷髅马",
  sniffer: "嗅探兽",
  snow_golem: "雪傀儡",
  squid: "鱿鱼",
  stray: "流浪者",
  strider: "炽足兽",
  tadpole: "蝌蚪",
  tropical_fish: "热带鱼",
  turtle: "海龟",
  vex: "恼鬼",
  vindicator: "卫道士",
  wandering_trader: "流浪商人",
  warden: "监守者",
  wither: "凋灵",
  wither_skeleton: "凋灵骷髅",
  zoglin: "僵尸疣猪兽",
  zombie_horse: "僵尸马",
  zombie_nautilus: "僵尸鹦鹉螺",
  zombie_villager: "僵尸村民",
  zombified_piglin: "僵尸猪灵",
  baby_cat: "幼年猫",
  baby_nautilus: "幼年鹦鹉螺",
  baby_pig: "幼年猪",
  baby_wolf: "幼年狼",
  wolf_angry: "愤怒的狼",
  wolf_big: "大型狼",
  wolf_cute: "可爱狼",
  wolf_grumpy: "暴躁狼",
  wolf_puglin: "巴哥狼",
  wolf_sad: "忧郁狼",

  armor: "护甲",
  equip: "装备",
  breakage: "损坏",

  bone_meal: "骨粉",
  dye: "染料",
  flintandsteel: "打火石",
  firecharge: "火焰弹",
  glow_ink_sac: "荧光墨囊",
};

function asTranslations(value: SoundTranslateValue | undefined): string[] {
  if (!value) return [];
  return typeof value === "string" ? [value] : Array.from(value).filter(Boolean);
}

function buildJoinedVariants(parts: string[][], limit: number): string[] {
  let acc: string[] = [""];
  for (const options of parts) {
    const next: string[] = [];
    const safeOptions = options.length ? options : [""];
    for (const prefix of acc) {
      for (const opt of safeOptions) {
        next.push(prefix + opt);
        if (next.length >= limit) break;
      }
      if (next.length >= limit) break;
    }
    acc = next.length ? next : acc;
    if (acc.length >= limit) break;
  }
  return acc.filter(Boolean);
}

function translateTokenVariantsZh(token: string, limit: number): string[] {
  const direct = asTranslations(sounds_translate_key[token]);
  if (direct.length) return direct.slice(0, limit);

  if (!token.includes("_")) return [];

  const parts = token.split("_").filter(Boolean);
  if (!parts.length) return [];

  const perPart = parts.map((p) => {
    const options = asTranslations(sounds_translate_key[p]);
    return options.length ? options : [p];
  });

  const joined = buildJoinedVariants(perPart, limit);
  return joined.length ? joined : [];
}

export function translateSoundTokenZh(token: string): string {
  const variants = translateTokenVariantsZh(token, 3);
  if (variants.length) return variants.join("/");
  return token;
}

export function translateSoundEventKeyZh(key: string): string {
  const tokens = key
    .trim()
    .replace(/[:]/g, ".")
    .split(/[.]/g)
    .filter(Boolean);

  if (!tokens.length) return "";

  return tokens.map((t) => translateSoundTokenZh(t)).join("·");
}

function translateSoundEventKeyZhVariants(key: string, limit: number): string[] {
  const tokens = key
    .trim()
    .replace(/[:]/g, ".")
    .split(/[.]/g)
    .filter(Boolean);

  if (!tokens.length) return [];

  const perToken = tokens.map((t) => {
    const v = translateTokenVariantsZh(t, 3);
    return v.length ? v : [t];
  });

  const joined = buildJoinedVariants(perToken.map((arr) => arr.map((v) => `${v}·`)), limit)
    .map((s) => s.replace(/·$/g, ""))
    .filter(Boolean);

  return joined.length ? joined : [];
}

function normalizeSoundSearchText(value: string): string {
  return value.toLowerCase().replace(/[^0-9a-z\u4e00-\u9fff]+/g, "");
}

export function buildSoundEventSearchText(key: string): string {
  const zh = translateSoundEventKeyZh(key);
  const zhVariants = translateSoundEventKeyZhVariants(key, 20);
  const loose = key.replace(/[:._]+/g, " ");
  return [key, loose, zh, ...zhVariants].filter(Boolean).join(" ");
}

export function fuzzyMatchSoundEventKey(key: string, query: string): boolean {
  const q = query.trim();
  if (!q) return true;

  const haystack = buildSoundEventSearchText(key);
  const haystackLower = haystack.toLowerCase();
  const haystackNormalized = normalizeSoundSearchText(haystackLower);
  const keyLower = key.toLowerCase();
  const keyNormalized = normalizeSoundSearchText(keyLower);

  const parts = q.split(/\s+/).filter(Boolean);
  return parts.every((part) => {
    const partLower = part.toLowerCase();
    const partNormalized = normalizeSoundSearchText(partLower);

    // English searches should stay tied to the actual event identifier. The
    // loose subsequence fallback is useful for Chinese transliterations, but
    // makes short English words match unrelated event names.
    if (/[a-z0-9]/i.test(partNormalized)) {
      return keyLower.includes(partLower) || keyNormalized.includes(partNormalized);
    }

    if (haystackLower.includes(partLower)) return true;

    if (!partNormalized) return true;
    if (haystackNormalized.includes(partNormalized)) return true;

    let i = 0;
    for (const ch of partNormalized) {
      const next = haystackNormalized.indexOf(ch, i);
      if (next < 0) return false;
      i = next + 1;
    }
    return true;
  });
}

function getSoundEventSearchPriority(key: string, query: string): number | null {
  const q = query.trim();
  if (!q) return 0;
  if (!fuzzyMatchSoundEventKey(key, q)) return null;

  const queryLower = q.toLowerCase();
  const queryNormalized = normalizeSoundSearchText(queryLower);
  const keyLower = key.toLowerCase();
  const keyNormalized = normalizeSoundSearchText(keyLower);

  if (keyLower === queryLower || keyNormalized === queryNormalized) return 0;

  const eventTokens = key
    .trim()
    .replace(/[:]/g, ".")
    .split(/[.]/g)
    .filter(Boolean);
  const searchableTokens = eventTokens.flatMap((token) => [
    token,
    ...translateTokenVariantsZh(token, 3),
  ]);
  const normalizedTokens = searchableTokens
    .map(normalizeSoundSearchText)
    .filter(Boolean);

  if (queryNormalized && normalizedTokens.includes(queryNormalized)) return 1;

  const translationNormalized = normalizeSoundSearchText(translateSoundEventKeyZh(key));
  if (queryNormalized && translationNormalized === queryNormalized) return 2;
  if (
    queryNormalized &&
    normalizedTokens.some((token) => token.startsWith(queryNormalized))
  ) return 3;
  if (
    queryNormalized &&
    normalizedTokens.some((token) => token.includes(queryNormalized))
  ) return 4;
  if (keyLower.startsWith(queryLower) || keyNormalized.startsWith(queryNormalized)) return 5;
  if (keyLower.includes(queryLower) || keyNormalized.includes(queryNormalized)) return 6;
  return 7;
}

export function searchSoundEventKeys(
  keys: readonly string[],
  query: string,
): string[] {
  const q = query.trim();
  if (!q) return [...keys];

  return keys
    .map((key, index) => ({
      index,
      key,
      priority: getSoundEventSearchPriority(key, q),
    }))
    .filter(
      (result): result is typeof result & { priority: number } =>
        result.priority !== null,
    )
    .sort((left, right) => left.priority - right.priority || left.index - right.index)
    .map((result) => result.key);
}
